### ISSUE TITLE
program get killed

### ISSUE THREAD

**Issue by touristCheng** [DrSleep/tensorflow-deeplab-resnet#125]
Hi~ I found the program get killed after running about 4600 steps, it seems to be suspended, no response for a long time, and then be killed. What may cause the problem? Thanks for your help! @DrSleep

**Comment by DrSleep** [comment]
Cannot really say anything without additional details. Maybe some
gpu-related problems.

On 24 Sep 2017 8:56 pm, "成硕" <notifications@github.com> wrote:

Hi~ I found the program get killed after running about 4600 steps, it seems
to be suspended, no response for a long time, and then be killed. What may
cause the problem? Thanks for your help! @DrSleep
<https://github.com/drsleep>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/DrSleep/tensorflow-deeplab-resnet/issues/125>, or mute
the thread

**Comment by Zumbalamambo** [comment]
@DrSleep is it possible to do semantic segmentation of human body ?say a separate colour for hand, leg etc..,
