### ISSUE TITLE
why the augmented segmentation data is different from the original PASCAL VOC dataset? 

### ISSUE THREAD

**Issue by NatalieZou** [DrSleep/tensorflow-deeplab-resnet#186]
I have download the augmented segmentation data from your link, and its different from the original PASCAL VOC dataset, won't it influence the result?
the augmented segmentation data:
![2007_000032](https://user-images.githubusercontent.com/32693588/42143577-71b02f0e-7de8-11e8-861d-9754ad5596f7.png)
![2007_000033](https://user-images.githubusercontent.com/32693588/42143622-a8439ea2-7de8-11e8-9565-e9557cfa6d96.png)
the original PASCAL VOC segmentation data:
![2007_000032](https://user-images.githubusercontent.com/32693588/42143628-b9a265fc-7de8-11e8-8c23-d4659250889e.png)
![2007_000033](https://user-images.githubusercontent.com/32693588/42143631-bc599a22-7de8-11e8-81ad-4149748f9fd9.png)

**Comment by DrSleep** [comment]
Ones are encoded without a colour map (top), ones - with (bottom). Otherwise, the images are the same.

Same question has been asked (and answered) many times already:
https://github.com/DrSleep/tensorflow-deeplab-resnet/issues/166
https://github.com/DrSleep/tensorflow-deeplab-resnet/issues/21
https://github.com/DrSleep/tensorflow-deeplab-resnet/issues/99
https://github.com/DrSleep/tensorflow-deeplab-resnet/issues/79
