### ISSUE TITLE
npy2ckpt.py error

### ISSUE THREAD

**Issue by amlarraz** [DrSleep/tensorflow-deeplab-resnet#23]
Hi! In the moment of weights conversion, I used npy2ckpt.py and give me the following error:

_ValueError: Variable bn4b2_branch2a/mean does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?_

To create the numpy file of weights, I used caffe-tensorflow, with pretrained .caffemodel you can download in [here](http://liangchiehchen.com/projects/DeepLabv2_resnet.html) and the deploy.prototxt you can see in [here](https://github.com/KaimingHe/deep-residual-networks/blob/master/prototxt/ResNet-101-deploy.prototxt).

**Comment by DrSleep** [comment]
Hi, did you use caffe-tensorflow from this repository?

**Comment by amlarraz** [comment]
Yes, I clone this repo just yesterday

**Comment by DrSleep** [comment]
I have run convert.py and npy2ckpt.py with your prototxt file, but it hasn't given the same error to me. Instead, I have got this one:

> ValueError: Variable fc1000/weights does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

which is due to the fact that there are no 'fc1000' layer in the DeepLab-Resnet model.
Anyway, could you please try to run convert.py and npy2ckpt.py with the deploy file provided in this repository and see whether it raises any errors?

**Comment by amlarraz** [comment]
Now perfect! I used your prototxt in misc and the weights download from [here](http://liangchiehchen.com/projects/DeepLabv2_resnet.html) and everything is ok.
Thank you very much.
