### ISSUE TITLE
how to do evaluation on the pascal server

### ISSUE THREAD

**Issue by gaopeng-eugene** [DrSleep/tensorflow-deeplab-resnet#37]
This is not a issue for your project. Recently, I upload the result.tgz to the pascal server. However, there is no response and submission results.
Do you know the reason?

**Comment by DrSleep** [comment]
Did you fill in all the fields when submitting? In my experience, leaving some field empty results in the behaviour that you have encountered

**Comment by arslan-chaudhry** [comment]
@gaopeng-eugene this could also happen when the format of your segmentation masks is not what the server is expecting. I faced something similar, when I tried to use the code to put colour palette on the segmentation masks from this repository. The server took 30 minutes and then exited with a weird error without providing any description. I later figured out that my format (colour palette) of segmentation mask is causing the problem, so I used my own code. Try using the following [script](https://github.com/arslan-chaudhry/tensorflow-deeplab-resnet/blob/master/test_voc.py) and see if it helps.

**Comment by salihkaragoz** [comment]
Hello,  
I know this place s not the proper for this question, sorry for that.

I try to evaluate my results on Pascal VOC Evaluation servers but I got an error and not enough definition. 
I convert my segmentation output array(WxH) to three depth array(WxHx3) for saving as a png image. 
I ve used to make_palette function to get the correct RGB value. also, there is also the same function in VOC DEVKIT. 
For example, Person RGB value is [W,H,x] = [192,128,128]

Do you have any idea about that? 

Thanks in advance...

**Comment by dongzhuoyao** [comment]
your upload image should be in 0~20, don't need colormap

**Comment by salihkaragoz** [comment]
Thank you for your interest. @dongzhuoyao 
I mean, My output is a 2D array(WxH) for only person segmentation so it includes 0(background) and 1 for(person.)
as I know, I have to convert these 2D arrays to image(WxHx3). I multiply the first layer with 192, the second layer with 128, the third layer with 128. 
Because I reviewed the sample result file from Pascal Voc site. I see segmentation results are PNGs and have different colors.

Am I wrong?

Also, I have changed [192,128,128] to [15,15,15] namely I have multiple all pixel with 15. Its almost the black.

 but i got same error. :-(

Same Error: **Error while evaluating challenge 6. Results were not generated properly. 
Error while submission. No scores were generated.** 

Its almost black, any idea? thank you so much btw 

![2008_000006](https://user-images.githubusercontent.com/22906895/36993215-440662bc-20be-11e8-87c3-4b0cda514f05.png)
