### ISSUE TITLE
How to perform multi-image inference

### ISSUE THREAD

**Issue by j50888** [DrSleep/tensorflow-deeplab-resnet#60]
Hi,

I want to change the inference.py to test multi-images
But I don't want to transform the input to batch
Because the current output mask will be the next input(I changed the framework to video object segmentation task and added additional input mask which from previous frame's output)

I first simply changed the original code with for-loop it will get error in this line 
`net = DeepLabResNetModel({'data': tf.expand_dims(img, dim=0)}, is_training=False)`

Then I tried to create the network only at first iteration and add this line
`net.layers['data'] = tf.expand_dims(img, dim=0)`
But it didn't change the data layer's content
The output masks all the same with the first iteration
How to modify the inference.py to iterativelly change the data layer?
Thanks!

**Comment by j50888** [comment]
BTW
I have a question that why the test image size not resizing and feed to the network it can work?(in inference.py)
I trained with image size 321x321 and tested with 854x480
It confused me

**Comment by DrSleep** [comment]
If I understood you correctly, the error that you are receiving is due to the variables created for the second time inside the loop. To solve it, you would need to reuse the created variables after the first iteration. For example, take a look at [these lines](https://github.com/DrSleep/tensorflow-deeplab-resnet/blob/master/evaluate_msc.py#L79-L84) from the multi-scale evaluation script: 
```python
    with tf.variable_scope('', reuse=False):
        net = DeepLabResNetModel({'data': image_batch}, is_training=False)
    with tf.variable_scope('', reuse=True):
        net075 = DeepLabResNetModel({'data': image_batch075}, is_training=False)
    with tf.variable_scope('', reuse=True):
        net05 = DeepLabResNetModel({'data': image_batch05}, is_training=False)
```

Regarding the second question: (in general), that is the beauty of fully convolutional networks! 
(Here), when you evaluate your trained model, each image is fed separately into the network (not in batches as during the training phase), so all the images preserve their original size, be it 321x321 or 854x480, or something else, and output masks of the corresponding sizes.

**Comment by j50888** [comment]
It works.
And I got the point how the network works.
Very thank you for the help and answering!

**Comment by NathanielNguyen11** [comment]
dear @j50888  . can you show your solotion? I did not understand what have to do? Thank you very much
